---
title: "IMPRESSIVE SQUIRTLE"
subtitle: "INFO 2950 Project"
format: html
editor: visual
---

The current generation has inherited a world that is on the decline, and those in power seem to be doing little to nothing to alleviate the weight put on our shoulders. Climate change is a multi-faceted issue, and according to NASA, the dramatic increase of human-caused CO2 emissions is a key factor in the severity of this problem. To further understand the connection between the ever increasing gap in so-called "developing" and "developed", as defined by the UN, our team has formed two research questions: In 2018, is the true proportion of developed countries with CO2 gas emissions above 1000 kilotons different than those with CO2 gas emissions below 1000 kilotons, and the second research question we will attempt to answer is if the true proportion of countries with a CO2 emission greater than the US in the twentieth century different from those in the twenty-first century. These two question tie in the variable of "developing" v "developed" and its correlation to CO2 production. To answer these two questions, we used null hypothesis testing. Regarding the first research question, we found that the data fails to provide convincing evidence that in 2018, the proportion of developed countries with CO2 gas emissions above 1000 kilotons is different than those with CO2 gas emissions below 1000 kilotons. Regarding the second research question, we found that the data provides convincing evidence that the true proportion of countries with a CO2 emission greater than the US in the twentieth century is different from those in the twenty-first century. From these results, we can form a conclusion that countries considered "developing" and "developed" and CO2 production - a strong contributor to climate change - have a relationships between them.
